name: Doxygen

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@1.9.5
      with:
        working-directory: './'
        doxyfile-path: 'doc/Doxygen'
