name: Doxygen

on:
  push:
    branches:
      - main
      - user_mie
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Generate Doxygen Documentation
      uses: mattnotmitt/doxygen-action@v1.9.5
      with:
        working-directory: 'submodule/'
        doxyfile-path: 'docs/Doxygen'
